/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppKeuanganRouteImport } from './routes/_app/keuangan'
import { Route as AppEventsEventIdRouteImport } from './routes/_app/events.$eventId'
import { Route as AppEventsNewRouteImport } from './routes/_app/events.new'
import { Route as AppPesananIndexRouteImport } from './routes/_app/pesanan/index'
import { Route as AppPesananNewRouteImport } from './routes/_app/pesanan/new'
import { Route as AppProfilIndexRouteImport } from './routes/_app/profil/index'
import { Route as AppProfilFeeRulesIndexRouteImport } from './routes/_app/profil/fee-rules/index'
import { Route as AppProfilFeeRulesFeeRuleIdRouteImport } from './routes/_app/profil/fee-rules/$feeRuleId'
import { Route as AppProfilFeeRulesNewRouteImport } from './routes/_app/profil/fee-rules/new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppKeuanganRoute = AppKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPesananIndexRoute = AppPesananIndexRouteImport.update({
  id: '/pesanan/',
  path: '/pesanan/',
  getParentRoute: () => AppRoute,
} as any)
const AppPesananNewRoute = AppPesananNewRouteImport.update({
  id: '/pesanan/new',
  path: '/pesanan/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilIndexRoute = AppProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilFeeRulesIndexRoute = AppProfilFeeRulesIndexRouteImport.update({
  id: '/profil/fee-rules/',
  path: '/profil/fee-rules/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilFeeRulesFeeRuleIdRoute =
  AppProfilFeeRulesFeeRuleIdRouteImport.update({
    id: '/profil/fee-rules/$feeRuleId',
    path: '/profil/fee-rules/$feeRuleId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProfilFeeRulesNewRoute = AppProfilFeeRulesNewRouteImport.update({
  id: '/profil/fee-rules/new',
  path: '/profil/fee-rules/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/keuangan': typeof AppKeuanganRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/events/new': typeof AppEventsNewRoute
  '/pesanan/new': typeof AppPesananNewRoute
  '/pesanan/': typeof AppPesananIndexRoute
  '/profil/': typeof AppProfilIndexRoute
  '/profil/fee-rules/$feeRuleId': typeof AppProfilFeeRulesFeeRuleIdRoute
  '/profil/fee-rules/new': typeof AppProfilFeeRulesNewRoute
  '/profil/fee-rules/': typeof AppProfilFeeRulesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/keuangan': typeof AppKeuanganRoute
  '/': typeof AppIndexRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/events/new': typeof AppEventsNewRoute
  '/pesanan/new': typeof AppPesananNewRoute
  '/pesanan': typeof AppPesananIndexRoute
  '/profil': typeof AppProfilIndexRoute
  '/profil/fee-rules/$feeRuleId': typeof AppProfilFeeRulesFeeRuleIdRoute
  '/profil/fee-rules/new': typeof AppProfilFeeRulesNewRoute
  '/profil/fee-rules': typeof AppProfilFeeRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/keuangan': typeof AppKeuanganRoute
  '/_app/': typeof AppIndexRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/pesanan/new': typeof AppPesananNewRoute
  '/_app/pesanan/': typeof AppPesananIndexRoute
  '/_app/profil/': typeof AppProfilIndexRoute
  '/_app/profil/fee-rules/$feeRuleId': typeof AppProfilFeeRulesFeeRuleIdRoute
  '/_app/profil/fee-rules/new': typeof AppProfilFeeRulesNewRoute
  '/_app/profil/fee-rules/': typeof AppProfilFeeRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/keuangan'
    | '/events/$eventId'
    | '/events/new'
    | '/pesanan/new'
    | '/pesanan/'
    | '/profil/'
    | '/profil/fee-rules/$feeRuleId'
    | '/profil/fee-rules/new'
    | '/profil/fee-rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/keuangan'
    | '/'
    | '/events/$eventId'
    | '/events/new'
    | '/pesanan/new'
    | '/pesanan'
    | '/profil'
    | '/profil/fee-rules/$feeRuleId'
    | '/profil/fee-rules/new'
    | '/profil/fee-rules'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/keuangan'
    | '/_app/'
    | '/_app/events/$eventId'
    | '/_app/events/new'
    | '/_app/pesanan/new'
    | '/_app/pesanan/'
    | '/_app/profil/'
    | '/_app/profil/fee-rules/$feeRuleId'
    | '/_app/profil/fee-rules/new'
    | '/_app/profil/fee-rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keuangan': {
      id: '/_app/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof AppKeuanganRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pesanan/': {
      id: '/_app/pesanan/'
      path: '/pesanan'
      fullPath: '/pesanan/'
      preLoaderRoute: typeof AppPesananIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pesanan/new': {
      id: '/_app/pesanan/new'
      path: '/pesanan/new'
      fullPath: '/pesanan/new'
      preLoaderRoute: typeof AppPesananNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/': {
      id: '/_app/profil/'
      path: '/profil'
      fullPath: '/profil/'
      preLoaderRoute: typeof AppProfilIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/fee-rules/': {
      id: '/_app/profil/fee-rules/'
      path: '/profil/fee-rules'
      fullPath: '/profil/fee-rules/'
      preLoaderRoute: typeof AppProfilFeeRulesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/fee-rules/$feeRuleId': {
      id: '/_app/profil/fee-rules/$feeRuleId'
      path: '/profil/fee-rules/$feeRuleId'
      fullPath: '/profil/fee-rules/$feeRuleId'
      preLoaderRoute: typeof AppProfilFeeRulesFeeRuleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/fee-rules/new': {
      id: '/_app/profil/fee-rules/new'
      path: '/profil/fee-rules/new'
      fullPath: '/profil/fee-rules/new'
      preLoaderRoute: typeof AppProfilFeeRulesNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppKeuanganRoute: typeof AppKeuanganRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppPesananNewRoute: typeof AppPesananNewRoute
  AppPesananIndexRoute: typeof AppPesananIndexRoute
  AppProfilIndexRoute: typeof AppProfilIndexRoute
  AppProfilFeeRulesFeeRuleIdRoute: typeof AppProfilFeeRulesFeeRuleIdRoute
  AppProfilFeeRulesNewRoute: typeof AppProfilFeeRulesNewRoute
  AppProfilFeeRulesIndexRoute: typeof AppProfilFeeRulesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppKeuanganRoute: AppKeuanganRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppEventsNewRoute: AppEventsNewRoute,
  AppPesananNewRoute: AppPesananNewRoute,
  AppPesananIndexRoute: AppPesananIndexRoute,
  AppProfilIndexRoute: AppProfilIndexRoute,
  AppProfilFeeRulesFeeRuleIdRoute: AppProfilFeeRulesFeeRuleIdRoute,
  AppProfilFeeRulesNewRoute: AppProfilFeeRulesNewRoute,
  AppProfilFeeRulesIndexRoute: AppProfilFeeRulesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
